#!/usr/bin/env bash

## install xcode-select
xcode-select --install
sudo xcodebuild -license accept

## Install brew
/bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
brew install ansible

## pull ansible
ansible-playbook local.yml --ask-vault-pass --ask-become-pass
# ansible-pull -U https://github.com/martinsrso/ansible.git
