- name: Ensure Homebrew is installled
  stat:
    path: /usr/local/bin/brew
  register: homebrew_check

- name: Fail if brew is not installed and install_homebrew_if_missing is false
  fail:
    msg: brew is missing...Install from http://brew.sh/
  when:
    - not homebrew_check.stat.exists
    - not install_homebrew_if_missing

- name: Installing Homebrew
  shell: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
  when:
    - not homebrew_check.stat.exists
    - install_homebrew_if_missing
  tags:
    - install
    - productivity
    - brew

- name: Updating Homebrew
  homebrew:
    update_homebrew: true
  when: homebrew_check.stat.exists
