- name: Installing Homebrew Cask Packages
  homebrew_cask:
    name: "{{ item }}"
    state: present
  register: result
  loop: '{{ brew_cask_packages }}'
  failed_when: >
    (result.changed != true)
  changed_when: >
    ("Error" in result.msg) or
    (result is successful)
  when: homebrew_check.stat.exists
