- name: Cloning .dotfiles
  ansible.builtin.git:
    repo: 'git@github.com:martinsrso/.dotfiles.git'
    dest: "{{ lookup('env', 'HOME') }}/.dotfiles"
    update: yes
    accept_hostkey: yes
    version: main
  tags:
    - install
    - dotfiles
- name: Stow dotfiles
  shell: cd $HOME/.dotfiles && ./macos
  tags:
    - install
    - dotfiles