- name: Install N
  npm:
    name: n
    global: yes
  tags:
    - install
    - node

- name: Install correct version of Node
  shell: >- 
    sudo mkdir -p /usr/local/n && sudo chown -R $(whoami) /usr/local/n && n lts
  tags:
    - install
    - node
