- name: Ensure OMZ is installled
  stat:
    path: "$HOME/.oh-my-zsh/"
  register: omz_check

- name: Oh-My-Zsh
  shell: curl -L https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh | sh
  when: not omz_check.stat.exists
  tags:
    - install
    - productivity
    - dotfiles
    - zsh

- name: Install zinit
  shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/zdharma/zinit/master/doc/install.sh)"
  when: not omz_check.stat.exists
  tags:
    - install
    - productivity
    - dotfiles
    - zsh
